// ─── FIFA World Cup 2026 Venue Data ────────────────────────────────────────────
// 16 official venues across USA, Canada, and Mexico

import type { Venue } from "@/types/venue.types";

/**
 * Mock venue data for the 2026 FIFA World Cup.
 * In production, this would be fetched from the FIFA official API.
 */
export const VENUES: readonly Venue[] = [
  {
    id: "metlife",
    name: "MetLife Stadium",
    city: "East Rutherford",
    state: "NJ",
    country: "USA",
    capacity: 82500,
    address: "1 MetLife Stadium Dr, East Rutherford, NJ 07073",
    timezone: "America/New_York",
    latitude: 40.8135,
    longitude: -74.0745,
    svgViewBox: "0 0 800 600",
    accessibilityFeatures: [
      "Wheelchair accessible seating in all sections",
      "Accessible restrooms on every level",
      "Audio description devices available",
      "Sign language interpretation at media events",
      "Tactile stadium maps at entry points",
      "Accessible parking in Lot H",
    ],
    transportOptions: ["NJ Transit bus", "Meadowlands Rail", "Shuttle from NYC", "Rideshare"],
    sustainabilityFeatures: [
      "100% renewable energy",
      "Zero-waste-to-landfill initiative",
      "EV charging stations",
      "Water recycling system",
    ],
    zones: [
      {
        id: "zone-north-entry",
        name: "North Entry Plaza",
        level: 0,
        capacity: 5000,
        type: "entry",
        accessibilityFeatures: ["Ramped access", "Wide turnstiles"],
        svgPath: "M100,50 L300,50 L300,150 L100,150 Z",
        centroid: { x: 200, y: 100 },
      },
      {
        id: "zone-south-entry",
        name: "South Entry Plaza",
        level: 0,
        capacity: 5000,
        type: "entry",
        accessibilityFeatures: ["Ramped access", "Wide turnstiles"],
        svgPath: "M100,450 L300,450 L300,550 L100,550 Z",
        centroid: { x: 200, y: 500 },
      },
      {
        id: "zone-lower-bowl",
        name: "Lower Bowl",
        level: 1,
        capacity: 40000,
        type: "seating",
        accessibilityFeatures: ["Wheelchair platforms", "Companion seating"],
        svgPath: "M200,150 L600,150 L600,450 L200,450 Z",
        centroid: { x: 400, y: 300 },
      },
      {
        id: "zone-upper-deck",
        name: "Upper Deck",
        level: 3,
        capacity: 30000,
        type: "seating",
        accessibilityFeatures: ["Elevator access", "Accessible restrooms nearby"],
        svgPath: "M150,100 L650,100 L650,500 L150,500 Z",
        centroid: { x: 400, y: 300 },
      },
      {
        id: "zone-food-court-a",
        name: "Food Court A (Main)",
        level: 1,
        capacity: 2000,
        type: "food",
        accessibilityFeatures: ["Lower counters", "Wide aisles"],
        svgPath: "M300,200 L450,200 L450,280 L300,280 Z",
        centroid: { x: 375, y: 240 },
      },
      {
        id: "zone-medical",
        name: "Medical Center",
        level: 0,
        capacity: 100,
        type: "medical",
        accessibilityFeatures: ["Full medical facilities", "AED stations"],
        svgPath: "M600,250 L680,250 L680,320 L600,320 Z",
        centroid: { x: 640, y: 285 },
      },
    ],
    waypoints: [
      {
        id: "wp-main-gate",
        name: "Main Gate",
        x: 400,
        y: 580,
        connectedTo: ["wp-concourse-south"],
        accessible: true,
        level: 0,
      },
      {
        id: "wp-concourse-south",
        name: "South Concourse",
        x: 400,
        y: 480,
        connectedTo: ["wp-main-gate", "wp-center-field", "wp-elevator-south"],
        accessible: true,
        level: 1,
      },
      {
        id: "wp-center-field",
        name: "Center Field View",
        x: 400,
        y: 300,
        connectedTo: ["wp-concourse-south", "wp-concourse-north", "wp-food-a"],
        accessible: true,
        level: 1,
      },
      {
        id: "wp-elevator-south",
        name: "South Elevator Bank",
        x: 350,
        y: 480,
        connectedTo: ["wp-concourse-south", "wp-upper-south"],
        accessible: true,
        level: 1,
      },
      {
        id: "wp-upper-south",
        name: "Upper Deck South",
        x: 350,
        y: 200,
        connectedTo: ["wp-elevator-south"],
        accessible: true,
        level: 3,
      },
      {
        id: "wp-food-a",
        name: "Food Court A",
        x: 375,
        y: 240,
        connectedTo: ["wp-center-field"],
        accessible: true,
        level: 1,
      },
      {
        id: "wp-concourse-north",
        name: "North Concourse",
        x: 400,
        y: 130,
        connectedTo: ["wp-center-field", "wp-north-exit"],
        accessible: true,
        level: 1,
      },
      {
        id: "wp-north-exit",
        name: "North Exit",
        x: 400,
        y: 50,
        connectedTo: ["wp-concourse-north"],
        accessible: true,
        level: 0,
      },
    ],
    faqs: [
      {
        id: "faq-1",
        question: "What items are prohibited at MetLife Stadium?",
        answer:
          "Prohibited items include: bags larger than 4.5\" x 6.5\", outside food and beverages, noise-making devices, selfie sticks, umbrellas, flags with poles, and any item deemed unsafe by security.",
        category: "safety",
        language: "en",
      },
      {
        id: "faq-2",
        question: "Where can I find accessible seating?",
        answer:
          "Accessible seating is available in all sections. Please visit the Accessibility Services Booth at Gate A or Gate D. Wheelchair accessible platforms are located throughout the lower bowl and upper deck.",
        category: "accessibility",
        language: "en",
      },
      {
        id: "faq-3",
        question: "What public transport options are available?",
        answer:
          "Take NJ Transit bus from Port Authority Bus Terminal. The Meadowlands Rail Line runs special game-day service from Secaucus Junction. Shuttle buses run from NYC Penn Station every 15 minutes starting 3 hours before kickoff.",
        category: "transport",
        language: "en",
      },
      {
        id: "faq-4",
        question: "Where are the first aid stations?",
        answer:
          "First aid stations are located at: Section 101 (Lower Bowl South), Section 237 (Upper Deck), and the main Medical Center at Gate C. AED devices are mounted every 200 feet throughout the stadium.",
        category: "safety",
        language: "en",
      },
    ],
  },
  {
    id: "sofistadium",
    name: "SoFi Stadium",
    city: "Inglewood",
    state: "CA",
    country: "USA",
    capacity: 70240,
    address: "1001 Stadium Dr, Inglewood, CA 90301",
    timezone: "America/Los_Angeles",
    latitude: 33.9535,
    longitude: -118.3392,
    svgViewBox: "0 0 800 600",
    accessibilityFeatures: [
      "Fully covered venue (accessible in all weather)",
      "300+ accessible seats",
      "Assistive listening devices",
      "Dedicated accessible drop-off zone",
    ],
    transportOptions: ["Metro K Line (Crenshaw)", "Shuttle from LAX", "Rideshare zone"],
    sustainabilityFeatures: [
      "LEED Gold certified",
      "Solar-powered roof",
      "Recycled water irrigation",
    ],
    zones: [
      {
        id: "zone-main-floor",
        name: "Main Floor",
        level: 0,
        capacity: 10000,
        type: "concourse",
        accessibilityFeatures: ["Fully flat surface", "Wide corridors"],
        svgPath: "M150,150 L650,150 L650,450 L150,450 Z",
        centroid: { x: 400, y: 300 },
      },
      {
        id: "zone-club-level",
        name: "Club Level",
        level: 2,
        capacity: 15000,
        type: "seating",
        accessibilityFeatures: ["Elevator access", "Premium accessible suites"],
        svgPath: "M200,100 L600,100 L600,200 L200,200 Z",
        centroid: { x: 400, y: 150 },
      },
    ],
    waypoints: [
      {
        id: "wp-west-plaza",
        name: "West Plaza Entry",
        x: 100,
        y: 300,
        connectedTo: ["wp-main-lobby"],
        accessible: true,
        level: 0,
      },
      {
        id: "wp-main-lobby",
        name: "Main Lobby",
        x: 400,
        y: 300,
        connectedTo: ["wp-west-plaza", "wp-field-level"],
        accessible: true,
        level: 0,
      },
      {
        id: "wp-field-level",
        name: "Field Level",
        x: 400,
        y: 500,
        connectedTo: ["wp-main-lobby"],
        accessible: true,
        level: 0,
      },
    ],
    faqs: [
      {
        id: "faq-sofi-1",
        question: "Is SoFi Stadium covered?",
        answer:
          "Yes! SoFi Stadium features a translucent roof covering the entire seating bowl, protecting fans from sun and rain while maintaining an open-air feel.",
        category: "general",
        language: "en",
      },
    ],
  },
  {
    id: "dallascowboys",
    name: "AT&T Stadium",
    city: "Arlington",
    state: "TX",
    country: "USA",
    capacity: 80000,
    address: "1 AT&T Way, Arlington, TX 76011",
    timezone: "America/Chicago",
    latitude: 32.7473,
    longitude: -97.0945,
    svgViewBox: "0 0 800 600",
    accessibilityFeatures: [
      "400+ accessible parking spaces",
      "Accessible seating on all levels",
      "Golf cart transport within stadium",
      "Braille menus at all concessions",
    ],
    transportOptions: ["Arlington Express shuttle", "Rideshare", "Parking on-site"],
    sustainabilityFeatures: [
      "LED lighting throughout",
      "Water conservation program",
      "Local food sourcing",
    ],
    zones: [
      {
        id: "zone-main-concourse",
        name: "Main Concourse",
        level: 1,
        capacity: 12000,
        type: "concourse",
        accessibilityFeatures: ["Wide walkways", "Escalator-free paths"],
        svgPath: "M100,100 L700,100 L700,500 L100,500 Z",
        centroid: { x: 400, y: 300 },
      },
    ],
    waypoints: [
      {
        id: "wp-att-main",
        name: "Main Gate",
        x: 400,
        y: 560,
        connectedTo: ["wp-att-concourse"],
        accessible: true,
        level: 0,
      },
      {
        id: "wp-att-concourse",
        name: "Main Concourse",
        x: 400,
        y: 300,
        connectedTo: ["wp-att-main"],
        accessible: true,
        level: 1,
      },
    ],
    faqs: [],
  },
];

/** Get a venue by ID */
export function getVenueById(id: string): Venue | undefined {
  return VENUES.find((v) => v.id === id);
}

/** Get venue IDs */
export const VENUE_IDS = VENUES.map((v) => v.id);
